using UnityEditor;
using UnityEngine;
using System.Reflection;
using System;

namespace WarpWorld.CrowdControl {
    [CustomEditor(typeof(CrowdControl))]
    class CrowdControlEditor : Editor {
        CrowdControl cc => target as CrowdControl;

        uint gameKey;
        FieldInfo gameKeyField;

        SerializedProperty effectEntries;

        void OnEnable() {
            gameKeyField = typeof(CrowdControl).GetField("_gameKey", BindingFlags.Instance | BindingFlags.NonPublic);
            gameKey = Convert.ToUInt32(gameKeyField.GetValue(target));
            effectEntries = serializedObject.FindProperty("ccEffectEntries");
        }

        public override void OnInspectorGUI() {
            base.OnInspectorGUI();

            EditorGUILayout.Space();
            EditorGUI.BeginChangeCheck();

            gameKey = Convert.ToUInt32(gameKeyField.GetValue(target));

            if (gameKey == 0) 
                EditorGUILayout.HelpBox("Missing game key. Only local test effects will be supported.", UnityEditor.MessageType.Error);

            EditorGUILayout.Space();
            GUI.enabled = !Application.isPlaying;
            if (GUILayout.Button("Generate Server Data")) GenerateServerData();

            if (Application.isPlaying) {
                EditorGUILayout.Space();

                GUI.enabled = cc.HasRunningEffects();
                if (GUILayout.Button("Stop All Effects"))
                    cc.StopAllEffects();
            }
        }

        void GenerateServerData() {
            // Put correctly generated byte-stream here
            Debug.LogWarning("Incomplete Feature");
        }
    }
}
